server:
  port: 8060
spring:
  application:
    name: hystrix
eureka:
  client:
    service-url:
      dafaultZone: http://loacalhost:8761:/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
